### PR TITLE
Using WINUSB_MS_VENDOR_CODE in extra string

### PR DESCRIPTION
**Pull request by karelbilek**
This might make some future debugging easier.

I did *not* test this, but it should work in theory :)

### CODE REVIEW

**Review by devanlai — CHANGES_REQUESTED** [review]
I'm not sure that this would work - I think it would create a temporary character array on the stack that would not be guaranteed to still be valid when the extra string descriptor request comes in.

This could be rectified by making it a static const char array.

**Comment by karelbilek** [comment]
You are probably right. I did not test it on our device yet (WinUSB still doesn't load correctly; I think I will have to add the extended properties descriptor).

**Comment by karelbilek** [comment]
It's static const now.

**Review by devanlai — APPROVED** [review]

**Comment by devanlai** [comment]
Thanks, when I get a chance to dig out my windows test machine, I'll verify that it still works.

**Comment by karelbilek** [comment]
Seems to be working in our FW 

https://github.com/trezor/trezor-mcu/pull/260

**Comment by devanlai** [comment]
@karel-3d Sorry this took so long to merge - I just finally got around to digging out my Windows 10 test machine. Thanks for the patch!

**Comment by karelbilek** [comment]
Ha I don’t work at the job I needed this for anymore. Thanks for replying
though :) and patching

.... now I remember all the USB debugging pain again. >:(

**Pull request merged**
